# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: false
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'Repositorio de código del proyecto de la localización española
    para el software de gestión integral Odoo. La localización española de Odoo incluye:
    - Módulos para adaptar el sistema a los requisitos fiscales y contables españoles.
    - Traducciones a las lenguas oficiales del país.'
repo_name: Localización española de Odoo
repo_slug: l10n-spain
repo_website: https://github.com/OCA/l10n-spain

