# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: "'Repositorio de código del proyecto de la localización española\n\
    \    para el software de gestión integral Odoo. La localización española de Odoo\
    \ incluye:\n    - Módulos para adaptar el sistema a los requisitos fiscales y\
    \ contables españoles.\n    - Traducciones a las lenguas oficiales del país.'"
repo_name: Localización española de Odoo
repo_slug: l10n-spain
repo_website: https://github.com/OCA/l10n-spain

